//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CateringItem
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> AmountLoaded { get; set; }
        public Nullable<int> AmountOffLoaded { get; set; }
        public Nullable<int> StationId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FlightId { get; set; }
    
        public virtual Airport Airport { get; set; }
        public virtual CateringItemCode CateringItemCode { get; set; }
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
