//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixTimeRoute
    {
        public string Route { get; set; }
        public Nullable<int> FixtTime { get; set; }
        public System.TimeSpan FixTime2 { get; set; }
    }
}
