//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFDP
    {
        public int FDPId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ScheduleName { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<System.DateTime> STDDayUTC { get; set; }
        public Nullable<System.DateTime> STADayUTC { get; set; }
        public string Flights { get; set; }
        public string Route { get; set; }
        public Nullable<int> Legs { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> ScheduledTime { get; set; }
        public Nullable<System.TimeSpan> FixTime2 { get; set; }
        public Nullable<int> FixTime { get; set; }
        public string DayName { get; set; }
        public string PDayName { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> PYear { get; set; }
        public string MonthName { get; set; }
        public string PMonthName { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> PMonth { get; set; }
        public string PDate { get; set; }
        public string PeriodFixTime { get; set; }
        public int Leg1 { get; set; }
        public int Leg2 { get; set; }
        public int Leg3 { get; set; }
        public int Leg4 { get; set; }
        public int Leg5 { get; set; }
        public int Leg6 { get; set; }
        public int Leg7 { get; set; }
        public int Leg8 { get; set; }
        public Nullable<System.TimeSpan> HFixTime2 { get; set; }
    }
}
