//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFDPItem
    {
        public int Id { get; set; }
        public int FDPId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<bool> IsSector { get; set; }
        public Nullable<bool> IsOff { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<bool> IsCanceled { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirportId { get; set; }
        public Nullable<int> ToAirportId { get; set; }
        public string FromAirport { get; set; }
        public string ToAirport { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> STDDayUTC { get; set; }
        public Nullable<System.DateTime> STADayUTC { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> ScheduledTime { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ScheduleName { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public Nullable<long> Rank { get; set; }
        public Nullable<int> FixedFlightTime { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
    }
}
