//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightChangeHistory
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string User { get; set; }
        public int FlightId { get; set; }
        public Nullable<int> OldRegisterId { get; set; }
        public string NewRegister { get; set; }
        public string OldRegister { get; set; }
        public Nullable<int> NewRegisterId { get; set; }
        public Nullable<System.DateTime> OldSTD { get; set; }
        public Nullable<System.DateTime> NewSTD { get; set; }
        public string OldFlightNumer { get; set; }
        public string NewFlightNumber { get; set; }
        public Nullable<int> OldFromAirportId { get; set; }
        public string OldToAirport { get; set; }
        public string NewToAirport { get; set; }
        public string OldFromAirport { get; set; }
        public string NewFromAirport { get; set; }
        public Nullable<int> NewFromAirportId { get; set; }
        public Nullable<int> OldStatusId { get; set; }
        public Nullable<int> NewStatusId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public Nullable<System.DateTime> OldOffBlock { get; set; }
        public Nullable<System.DateTime> NewOffBlock { get; set; }
        public Nullable<System.DateTime> OldTakeOff { get; set; }
        public Nullable<System.DateTime> NewTakeOff { get; set; }
        public Nullable<System.DateTime> OldLanding { get; set; }
        public Nullable<System.DateTime> NewLanding { get; set; }
        public Nullable<System.DateTime> OldOnBlock { get; set; }
        public Nullable<System.DateTime> NewOnBlock { get; set; }
        public Nullable<int> OldToAirportId { get; set; }
        public Nullable<int> NewToAirportId { get; set; }
        public Nullable<System.DateTime> OldSTA { get; set; }
        public Nullable<System.DateTime> NewSTA { get; set; }
    }
}
