//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDailyRosterFlight
    {
        public int Id { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public string FromAirportIATA { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string ToAirportIATA { get; set; }
        public string Register { get; set; }
        public Nullable<int> CrewId { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
    }
}
