//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCrewCertificatesSummary
    {
        public string Name { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public Nullable<System.DateTime> MedicalLastCheckup { get; set; }
        public Nullable<System.DateTime> MedicalNextChechup { get; set; }
        public int IsMedicalExpired { get; set; }
        public Nullable<int> RemainMedical { get; set; }
        public Nullable<System.DateTime> LPRExpireDate { get; set; }
        public int IsLPRExpired { get; set; }
        public Nullable<int> RemainLPR { get; set; }
        public Nullable<System.DateTime> ProficiencyCheckDate { get; set; }
        public Nullable<System.DateTime> ProficiencyExpireDate { get; set; }
        public Nullable<int> RemainProficiency { get; set; }
        public int IsProficiencyExpired { get; set; }
        public Nullable<System.DateTime> CMCExpireDate { get; set; }
        public Nullable<int> RemainCMC { get; set; }
        public int IsCMCExpired { get; set; }
        public Nullable<System.DateTime> CCRMIssueDate { get; set; }
        public Nullable<System.DateTime> CCRMExpireDate { get; set; }
        public Nullable<int> RemainCCRM { get; set; }
        public int IsCCRMExpired { get; set; }
        public Nullable<System.DateTime> AvSecIssueDate { get; set; }
        public Nullable<System.DateTime> AvSecExpireDate { get; set; }
        public Nullable<int> RemainAvSec { get; set; }
        public int IsAvSecExpired { get; set; }
        public Nullable<System.DateTime> SEPTIssueDate { get; set; }
        public Nullable<System.DateTime> SEPTExpireDate { get; set; }
        public Nullable<int> RemainSEPT { get; set; }
        public int IsSEPTExpired { get; set; }
        public Nullable<System.DateTime> SEPTPracticalIssueDate { get; set; }
        public Nullable<System.DateTime> SEPTPracticalExpireDate { get; set; }
        public Nullable<int> RemainSEPTP { get; set; }
        public int IsSEPTPExpired { get; set; }
        public Nullable<System.DateTime> DGIssueDate { get; set; }
        public Nullable<System.DateTime> DGExpireDate { get; set; }
        public Nullable<int> RemainDG { get; set; }
        public int IsDGExpired { get; set; }
        public Nullable<System.DateTime> SMSIssueDate { get; set; }
        public Nullable<System.DateTime> SMSExpireDate { get; set; }
        public Nullable<int> RemainSMS { get; set; }
        public int IsSMSExpired { get; set; }
        public Nullable<System.DateTime> FirstAidIssueDate { get; set; }
        public Nullable<System.DateTime> FirstAidExpireDate { get; set; }
        public Nullable<int> RemainFirstAid { get; set; }
        public int IsFirstAidExpired { get; set; }
        public Nullable<System.DateTime> ColdWeatherIssueDate { get; set; }
        public Nullable<System.DateTime> ColdWeatherExpireDate { get; set; }
        public Nullable<int> RemainColdWeather { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public Nullable<System.DateTime> HotWeatherIssueDate { get; set; }
        public Nullable<System.DateTime> HotWeatherExpireDate { get; set; }
        public Nullable<int> RemainHotWeather { get; set; }
        public int IsHotWeatherExpired { get; set; }
    }
}
