//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDelayMonthlyCategory
    {
        public string Category { get; set; }
        public int PassedYear { get; set; }
        public int MonthOfYear { get; set; }
        public string YearStr { get; set; }
        public string MonthStr { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> MonthFrom { get; set; }
        public Nullable<System.DateTime> MonthTo { get; set; }
        public string MonthFromPersian { get; set; }
        public string MonthToPersian { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string DateFromPersian { get; set; }
        public string DateToPersian { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Delay { get; set; }
        public Nullable<int> TotalFlights { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
    }
}
