//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRosterSheet
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public string Register { get; set; }
        public string FlightNumber { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string Route { get; set; }
        public string FSTDLocal { get; set; }
        public string FSTALocal { get; set; }
        public string FSTD { get; set; }
        public string FSTA { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public string Duration { get; set; }
        public Nullable<int> DurationMinutes { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public int IsCanceled { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<int> FlightTimeActual { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> IP1 { get; set; }
        public string IP1Name { get; set; }
        public Nullable<bool> IP1DH { get; set; }
        public Nullable<int> IP2 { get; set; }
        public string IP2Name { get; set; }
        public Nullable<bool> IP2DH { get; set; }
        public Nullable<int> P11 { get; set; }
        public string P11Name { get; set; }
        public Nullable<bool> P11DH { get; set; }
        public Nullable<int> P12 { get; set; }
        public string P12Name { get; set; }
        public Nullable<bool> P12DH { get; set; }
        public Nullable<int> P13 { get; set; }
        public string P13Name { get; set; }
        public Nullable<bool> P13DH { get; set; }
        public Nullable<int> P14 { get; set; }
        public string P14Name { get; set; }
        public Nullable<bool> P14DH { get; set; }
        public Nullable<int> P15 { get; set; }
        public string P15Name { get; set; }
        public Nullable<bool> P15DH { get; set; }
        public Nullable<int> P21 { get; set; }
        public string P21Name { get; set; }
        public Nullable<bool> P21DH { get; set; }
        public Nullable<int> P22 { get; set; }
        public string P22Name { get; set; }
        public Nullable<bool> P22DH { get; set; }
        public Nullable<int> P23 { get; set; }
        public string P23Name { get; set; }
        public Nullable<bool> P23DH { get; set; }
        public Nullable<int> P24 { get; set; }
        public string P24Name { get; set; }
        public Nullable<bool> P24DH { get; set; }
        public Nullable<int> P25 { get; set; }
        public string P25Name { get; set; }
        public Nullable<bool> P25DH { get; set; }
        public Nullable<int> Safety1 { get; set; }
        public string Safety1Name { get; set; }
        public Nullable<bool> Safety1DH { get; set; }
        public Nullable<int> Safety2 { get; set; }
        public string Safety2Name { get; set; }
        public Nullable<bool> Safety2DH { get; set; }
        public Nullable<int> ISCCM1 { get; set; }
        public string ISCCM1Name { get; set; }
        public Nullable<bool> ISCCM1DH { get; set; }
        public Nullable<int> SCCM1 { get; set; }
        public string SCCM1Name { get; set; }
        public Nullable<bool> SCCM1DH { get; set; }
        public Nullable<int> SCCM2 { get; set; }
        public string SCCM2Name { get; set; }
        public Nullable<bool> SCCM2DH { get; set; }
        public Nullable<int> SCCM3 { get; set; }
        public Nullable<int> SCCM4 { get; set; }
        public Nullable<int> SCCM5 { get; set; }
        public string SCCM3Name { get; set; }
        public string SCCM4Name { get; set; }
        public string SCCM5Name { get; set; }
        public Nullable<bool> SCCM3DH { get; set; }
        public Nullable<bool> SCCM4DH { get; set; }
        public Nullable<bool> SCCM5DH { get; set; }
        public Nullable<int> CCM1 { get; set; }
        public string CCM1Name { get; set; }
        public Nullable<bool> CCM1DH { get; set; }
        public Nullable<int> CCM2 { get; set; }
        public string CCM2Name { get; set; }
        public Nullable<bool> CCM2DH { get; set; }
        public Nullable<int> CCM3 { get; set; }
        public string CCM3Name { get; set; }
        public Nullable<bool> CCM3DH { get; set; }
        public Nullable<int> CCM4 { get; set; }
        public string CCM4Name { get; set; }
        public Nullable<bool> CCM4DH { get; set; }
        public Nullable<int> CCM5 { get; set; }
        public string CCM5Name { get; set; }
        public Nullable<bool> CCM5DH { get; set; }
        public Nullable<int> OBS1 { get; set; }
        public string OBS1Name { get; set; }
        public Nullable<bool> OBS1DH { get; set; }
        public Nullable<int> OBS2 { get; set; }
        public string OBS2Name { get; set; }
        public Nullable<bool> OBS2DH { get; set; }
        public Nullable<int> CHECK1 { get; set; }
        public string CHECK1Name { get; set; }
        public Nullable<bool> CHECK1DH { get; set; }
        public Nullable<int> CHECK2 { get; set; }
        public string CHECK2Name { get; set; }
        public Nullable<bool> CHECK2DH { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public string DeadHeads { get; set; }
        public string Color1 { get; set; }
        public string Color2 { get; set; }
    }
}
