//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDelayDailyAirportCategory
    {
        public System.DateTime Date { get; set; }
        public string DayName { get; set; }
        public string YearName { get; set; }
        public string PDate { get; set; }
        public string PYearName { get; set; }
        public string PMonthName { get; set; }
        public string PDayName { get; set; }
        public string Airport { get; set; }
        public string Category { get; set; }
        public int Delay { get; set; }
        public int Count { get; set; }
        public Nullable<int> TotalFlights { get; set; }
        public int BlockTime { get; set; }
        public int FlightTime { get; set; }
        public Nullable<double> DelayLeg { get; set; }
        public Nullable<double> DelayRatio { get; set; }
        public Nullable<double> TRND { get; set; }
        public Nullable<double> TRNDLeg { get; set; }
    }
}
