//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLayOver
    {
        public int Id { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public string FlightNumber { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> BaseAirportId { get; set; }
        public int IsLayOver { get; set; }
    }
}
