//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCrew
    {
        public int Id { get; set; }
        public string ImageUrl { get; set; }
        public string PID { get; set; }
        public int PersonId { get; set; }
        public Nullable<System.DateTime> DateJoinCompany { get; set; }
        public Nullable<int> ExpCompany { get; set; }
        public Nullable<System.DateTime> DateRegister { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DateConfirmed { get; set; }
        public bool IsDeleted { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int MarriageId { get; set; }
        public string NID { get; set; }
        public int SexId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string Email { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Mobile { get; set; }
        public string FaxTelNumber { get; set; }
        public string PassportNumber { get; set; }
        public Nullable<System.DateTime> DatePassportIssue { get; set; }
        public Nullable<System.DateTime> DatePassportExpire { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> DateJoinAvation { get; set; }
        public Nullable<int> Exp { get; set; }
        public Nullable<System.DateTime> DateLastCheckUP { get; set; }
        public Nullable<System.DateTime> DateNextCheckUP { get; set; }
        public Nullable<System.DateTime> DateYearOfExperience { get; set; }
        public string CaoCardNumber { get; set; }
        public Nullable<System.DateTime> DateCaoCardIssue { get; set; }
        public string CompetencyNo { get; set; }
        public Nullable<int> CaoInterval { get; set; }
        public Nullable<System.DateTime> DateCaoCardExpire { get; set; }
        public int IsMedicalExpired { get; set; }
        public Nullable<int> BaseAirportId { get; set; }
        public Nullable<int> CurrentLocationAirportId { get; set; }
        public string CurrentLocationAirporIATA { get; set; }
        public Nullable<int> LastLocationId { get; set; }
        public string LastLocation { get; set; }
        public string CurrentLocationCity { get; set; }
        public Nullable<int> CurrentLocationCityId { get; set; }
        public int AvStatusId { get; set; }
        public string AvStatus { get; set; }
        public int IsAvSecExpired { get; set; }
        public int IsCCRMExpired { get; set; }
        public int IsCMCExpired { get; set; }
        public int IsColdWeatherExpired { get; set; }
        public int IsCRMExpired { get; set; }
        public int IsDGExpired { get; set; }
        public int IsHotWeatherExpired { get; set; }
        public int IsLicenceExpired { get; set; }
        public int IsLicenceIRExpired { get; set; }
        public int IsLPRExpired { get; set; }
        public int IsFirstAidExpired { get; set; }
        public Nullable<int> RemainFirstAid { get; set; }
        public int IsPassportExpired { get; set; }
        public int IsProficiencyExpired { get; set; }
        public int IsSEPTExpired { get; set; }
        public int IsSEPTPExpired { get; set; }
        public int IsSMSExpired { get; set; }
        public int IsUpsetRecoveryTrainingExpired { get; set; }
        public Nullable<int> RemainAvSec { get; set; }
        public Nullable<int> RemainCAO { get; set; }
        public Nullable<int> RemainCCRM { get; set; }
        public Nullable<int> RemainCMC { get; set; }
        public Nullable<int> RemainColdWeather { get; set; }
        public Nullable<int> RemainCRM { get; set; }
        public Nullable<int> RemainDG { get; set; }
        public Nullable<int> RemainHotWeather { get; set; }
        public Nullable<int> RemainLicence { get; set; }
        public Nullable<int> RemainLicenceIR { get; set; }
        public Nullable<int> RemainLPR { get; set; }
        public Nullable<int> RemainMedical { get; set; }
        public Nullable<int> RemainPassport { get; set; }
        public Nullable<int> RemainProficiency { get; set; }
        public Nullable<int> RemainProficiencyOPC { get; set; }
        public Nullable<int> RemainSEPT { get; set; }
        public Nullable<int> RemainSEPTP { get; set; }
        public Nullable<int> RemainSMS { get; set; }
        public Nullable<int> RemainUpsetRecoveryTraining { get; set; }
        public string ScheduleName { get; set; }
        public string Code { get; set; }
        public int GroupOrder { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> InActive { get; set; }
        public System.DateTime DateInactiveBegin { get; set; }
        public System.DateTime DateInactiveEnd { get; set; }
        public int IsCockpit { get; set; }
        public int IsCabin { get; set; }
        public Nullable<int> AircraftTypeId { get; set; }
        public Nullable<System.DateTime> DateTypeIssue { get; set; }
        public Nullable<System.DateTime> DateTypeExpire { get; set; }
        public string ValidTypes { get; set; }
        public double FlightSum { get; set; }
        public int FlightEarly { get; set; }
        public int FlightLate { get; set; }
        public Nullable<System.DateTime> MedicalExpired { get; set; }
        public Nullable<System.DateTime> CMCExpired { get; set; }
        public Nullable<System.DateTime> SEPTExpired { get; set; }
        public Nullable<System.DateTime> DGExpired { get; set; }
        public Nullable<System.DateTime> CCRMExpired { get; set; }
        public Nullable<System.DateTime> SMSExpired { get; set; }
        public Nullable<System.DateTime> AvSecExpired { get; set; }
        public Nullable<System.DateTime> LPCExpired { get; set; }
        public Nullable<System.DateTime> LPRExpired { get; set; }
        public Nullable<System.DateTime> FirstAidExpired { get; set; }
        public Nullable<System.DateTime> LicenceExpired { get; set; }
        public Nullable<int> RemainTRI { get; set; }
        public Nullable<int> RemainTRE { get; set; }
        public Nullable<int> RemainRecurrent { get; set; }
        public Nullable<int> RemainLine { get; set; }
        public int IsRecurrentExpired { get; set; }
        public int IsLineExpired { get; set; }
        public int IsTRIExpired { get; set; }
        public int IsTREExpired { get; set; }
        public Nullable<System.DateTime> MedicalIssued { get; set; }
        public Nullable<System.DateTime> SEPTIssued { get; set; }
        public Nullable<System.DateTime> SEPTPIssued { get; set; }
        public Nullable<System.DateTime> SEPTPExpired { get; set; }
        public Nullable<System.DateTime> DGIssued { get; set; }
        public Nullable<System.DateTime> CCRMIssued { get; set; }
        public Nullable<System.DateTime> CRMIssued { get; set; }
        public Nullable<System.DateTime> CRMExpired { get; set; }
        public Nullable<System.DateTime> SMSIssued { get; set; }
        public Nullable<System.DateTime> AvSecIssued { get; set; }
        public Nullable<System.DateTime> ColdWXIssued { get; set; }
        public Nullable<System.DateTime> HotWXIssued { get; set; }
        public Nullable<System.DateTime> ColdWXExpired { get; set; }
        public Nullable<System.DateTime> HotWXExpired { get; set; }
        public Nullable<System.DateTime> FirstAidIssued { get; set; }
        public Nullable<System.DateTime> LineIssued { get; set; }
        public Nullable<System.DateTime> LineExpired { get; set; }
        public Nullable<System.DateTime> RecurrentIssued { get; set; }
        public Nullable<System.DateTime> RecurrentExpired { get; set; }
        public Nullable<System.DateTime> TREExpired { get; set; }
        public Nullable<System.DateTime> TRIExpired { get; set; }
        public Nullable<System.DateTime> LPCIssued { get; set; }
        public Nullable<System.DateTime> OPCIssued { get; set; }
        public Nullable<System.DateTime> OPCExpired { get; set; }
        public Nullable<System.DateTime> LicenceIssued { get; set; }
    }
}
