//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCateringItem
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> AmountLoaded { get; set; }
        public Nullable<int> AmountOffLoaded { get; set; }
        public Nullable<int> StationId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string IATA { get; set; }
        public string ICAO { get; set; }
        public string Register { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
    }
}
