//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewLogBook18
    {
        public System.DateTime Date { get; set; }
        public string DepStn { get; set; }
        public string ArrStn { get; set; }
        public string FltNo { get; set; }
        public string ACReg { get; set; }
        public string ACType { get; set; }
        public Nullable<System.DateTime> OffBlock { get; set; }
        public Nullable<System.DateTime> OffBlockLocal { get; set; }
        public Nullable<System.DateTime> OnBlock { get; set; }
        public Nullable<System.DateTime> OnBlockLocal { get; set; }
        public Nullable<int> DayTakeOff { get; set; }
        public Nullable<int> NightTakeOff { get; set; }
        public Nullable<int> DayLanding { get; set; }
        public Nullable<int> NightLanding { get; set; }
        public Nullable<int> NightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> MultiPilotTime { get; set; }
        public Nullable<int> IFRTime { get; set; }
        public Nullable<int> PICTime { get; set; }
        public Nullable<int> COPILOTTime { get; set; }
        public Nullable<int> IPTime { get; set; }
        public Nullable<int> DUALTime { get; set; }
        public string Pos { get; set; }
        public string Dep2 { get; set; }
        public string Arr2 { get; set; }
        public string PICName { get; set; }
    }
}
