//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Report
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCourseNew
    {
        public int Id { get; set; }
        public int CourseTypeId { get; set; }
        public string CourseType { get; set; }
        public Nullable<int> CertificateTypeId { get; set; }
        public string CertificateType { get; set; }
        public string JobGroups { get; set; }
        public string JobGroupsCode { get; set; }
        public System.DateTime DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public string Instructor { get; set; }
        public string Location { get; set; }
        public string Department { get; set; }
        public Nullable<int> OrganizationId { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> DurationUnitId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string TrainingDirector { get; set; }
        public string Title { get; set; }
        public bool Recurrent { get; set; }
        public Nullable<int> Interval { get; set; }
        public Nullable<int> CalanderTypeId { get; set; }
        public Nullable<bool> IsInside { get; set; }
        public Nullable<bool> IsGeneral { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string No { get; set; }
        public Nullable<bool> IsNotificationEnabled { get; set; }
        public string Sessions { get; set; }
        public int PeopleCount { get; set; }
        public string Organization { get; set; }
        public string DurationUnit { get; set; }
        public string CalendarType { get; set; }
        public Nullable<bool> Continual { get; set; }
        public Nullable<int> Mandatory { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<int> InstructorEmployeeId { get; set; }
        public string InstructorJobGroup { get; set; }
        public string HoldingType { get; set; }
        public Nullable<bool> InForm { get; set; }
        public Nullable<bool> SendLetter { get; set; }
        public Nullable<bool> Financial { get; set; }
        public Nullable<bool> Certificate { get; set; }
        public Nullable<int> Instructor2Id { get; set; }
        public Nullable<int> Instructor2EmployeeId { get; set; }
        public string Instructor2JobGroup { get; set; }
        public string Instructor2 { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public string SMSIns1 { get; set; }
        public string SMSIns2 { get; set; }
        public string SMSIns1Status { get; set; }
        public string SMSIns2Status { get; set; }
        public Nullable<System.DateTime> SMSInsDate { get; set; }
        public string AttForm { get; set; }
    }
}
