//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_SC
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string remark2 { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
