//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FLTGroupItem
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public int FLTGroupId { get; set; }
    
        public virtual FLTGroup FLTGroup { get; set; }
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
