//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Idea
    {
        public string PID { get; set; }
        public string NID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public string ClassID { get; set; }
        public string instructor { get; set; }
        public string BeginDate { get; set; }
        public string EndDate { get; set; }
        public string Days { get; set; }
        public string Location { get; set; }
        public string City { get; set; }
        public string issue { get; set; }
        public string expire { get; set; }
        public System.Guid Id { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
