//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptDelayLegMap
    {
        public int ID { get; set; }
        public int FlightId { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public string PDate { get; set; }
        public int DelayCodeId { get; set; }
        public string Code { get; set; }
        public Nullable<int> Delay { get; set; }
        public string Remark { get; set; }
        public string Categoty { get; set; }
        public string CategoryIATA { get; set; }
        public string MapTitle { get; set; }
        public string MapTitle2 { get; set; }
    }
}
