//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFDPMonthlyPersian
    {
        public int PYear { get; set; }
        public string PeriodFixTime { get; set; }
        public int CrewId { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ScheduleName { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FixTime { get; set; }
        public Nullable<int> ScheduledTime { get; set; }
        public Nullable<int> Legs { get; set; }
        public Nullable<int> Leg1 { get; set; }
        public Nullable<int> Leg2 { get; set; }
        public Nullable<int> Leg3 { get; set; }
        public Nullable<int> Leg4 { get; set; }
        public Nullable<int> Leg5 { get; set; }
        public Nullable<int> Leg6 { get; set; }
        public Nullable<int> Leg7 { get; set; }
        public Nullable<int> Leg8 { get; set; }
        public int RankOrder { get; set; }
        public Nullable<int> StandBy { get; set; }
        public Nullable<int> Misson { get; set; }
        public Nullable<int> FixTimeTotal { get; set; }
        public Nullable<int> FX300000 { get; set; }
        public Nullable<int> FX300001 { get; set; }
        public Nullable<int> FX300002 { get; set; }
        public Nullable<int> FX300003 { get; set; }
        public Nullable<int> FX300004 { get; set; }
        public Nullable<int> FX300005 { get; set; }
        public Nullable<int> FX300006 { get; set; }
        public Nullable<int> FX300007 { get; set; }
        public Nullable<int> FX300008 { get; set; }
        public Nullable<int> FX300009 { get; set; }
    }
}
