//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RptFDPMonthly
    {
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string JobGroupRoot { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FixTime { get; set; }
        public Nullable<int> ScheduledTime { get; set; }
        public Nullable<int> Legs { get; set; }
        public Nullable<int> Leg1 { get; set; }
        public Nullable<int> Leg2 { get; set; }
        public Nullable<int> Leg3 { get; set; }
        public Nullable<int> Leg4 { get; set; }
        public Nullable<int> Leg5 { get; set; }
        public Nullable<int> Leg6 { get; set; }
        public Nullable<int> Leg7 { get; set; }
        public Nullable<int> Leg8 { get; set; }
    }
}
