//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDayDuty7
    {
        public System.DateTime Date { get; set; }
        public int CrewId { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> DurationLocal { get; set; }
        public Nullable<int> Duty7 { get; set; }
        public Nullable<double> Duty7Local { get; set; }
    }
}
