//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCrewTime
    {
        public int Id { get; set; }
        public string PID { get; set; }
        public string Name { get; set; }
        public System.DateTime CDate { get; set; }
        public int BoxId { get; set; }
        public string DateStr { get; set; }
        public int Positioning { get; set; }
        public int Day1_Flight { get; set; }
        public int Day7_Flight { get; set; }
        public int Day14_Flight { get; set; }
        public int Day28_Flight { get; set; }
        public int Year_Flight { get; set; }
        public int CYear_Flight { get; set; }
        public double Day1_Duty { get; set; }
        public double Day7_Duty { get; set; }
        public double Day14_Duty { get; set; }
        public double Day28_Duty { get; set; }
        public int Year_Duty { get; set; }
        public int CalendarStatusId { get; set; }
        public string CalendarStatus { get; set; }
        public int ECSplitedId { get; set; }
        public int ECId { get; set; }
        public System.DateTime ECDateStartLocal { get; set; }
        public System.DateTime ECDateEndLocal { get; set; }
        public System.DateTime ECDateStart { get; set; }
        public System.DateTime ECDateEnd { get; set; }
        public Nullable<int> ECDuty { get; set; }
        public int ECBoxId { get; set; }
        public decimal FDPReduction { get; set; }
        public int Error_Day28_Flight { get; set; }
        public int Error_Year_Flight { get; set; }
        public int Error_CYear_Flight { get; set; }
        public int Error_Day7_Duty { get; set; }
        public int Error_Day14_Duty { get; set; }
        public int Error_Day28_Duty { get; set; }
    }
}
