//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightSecurityDH
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string FlightType { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Customer { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Register { get; set; }
        public string AircraftType { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public string CPT { get; set; }
        public string CPT2 { get; set; }
        public string OBSP1 { get; set; }
        public string IP { get; set; }
        public string IP2 { get; set; }
        public string Safety { get; set; }
        public string FO { get; set; }
        public string FO2 { get; set; }
        public string OBSP2 { get; set; }
        public string ISCCM { get; set; }
        public string Purser { get; set; }
        public string Purser2 { get; set; }
        public string Purser3 { get; set; }
        public string FA1 { get; set; }
        public string FA2 { get; set; }
        public string FA3 { get; set; }
        public string FA4 { get; set; }
        public string CAOBS1 { get; set; }
        public string CAOBS2 { get; set; }
        public string CAOBS3 { get; set; }
        public string CAOBS4 { get; set; }
        public string CACheck1 { get; set; }
        public string CACheck2 { get; set; }
        public string CACheck3 { get; set; }
        public string CACheck4 { get; set; }
    }
}
