//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRoute
    {
        public int Id { get; set; }
        public int FromAirport { get; set; }
        public string FromAirportIATA { get; set; }
        public int ToAirport { get; set; }
        public string ToAirportIATA { get; set; }
        public string Route { get; set; }
        public Nullable<int> FlightH { get; set; }
        public Nullable<int> FlightM { get; set; }
    }
}
