//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightCrewNewXTime
    {
        public int FDPId { get; set; }
        public int FDPItemId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int SexId { get; set; }
        public int GroupOrder { get; set; }
        public int IsCockpit { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> FlightTimeActual { get; set; }
        public Nullable<int> FixTime { get; set; }
        public Nullable<int> SITATime { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
    }
}
