//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewWeek
    {
        public System.DateTime Date { get; set; }
        public Nullable<int> PassedDay { get; set; }
        public Nullable<int> PassedWeek { get; set; }
        public Nullable<int> PassedMonth { get; set; }
        public Nullable<int> PassedYear { get; set; }
        public Nullable<int> DayOfMonth { get; set; }
        public Nullable<int> DayOfWeek { get; set; }
        public Nullable<int> WeekOfMonth { get; set; }
        public Nullable<int> MonthOfYear { get; set; }
        public Nullable<long> Rank { get; set; }
        public Nullable<long> RankDesc { get; set; }
        public Nullable<long> RankMonth { get; set; }
        public Nullable<long> RankMonthDesc { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
    }
}
