//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFormAYearly
    {
        public int Year { get; set; }
        public Nullable<int> Legs { get; set; }
        public Nullable<decimal> FlightHour { get; set; }
        public Nullable<int> PaxChild { get; set; }
        public Nullable<int> PaxInfant { get; set; }
        public Nullable<int> PaxAdult { get; set; }
        public Nullable<int> PaxTotal { get; set; }
        public Nullable<double> PaxTotalDistRound { get; set; }
        public Nullable<double> PaxTotalDist { get; set; }
        public Nullable<int> PaxAll { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<double> TotalSeatDist { get; set; }
        public Nullable<int> PaxLoad { get; set; }
        public Nullable<double> TotalSeatDistRound { get; set; }
        public Nullable<int> PaxAllWeight { get; set; }
        public Nullable<double> PaxAllWeightDistance { get; set; }
        public Nullable<int> BaggageWeight { get; set; }
        public Nullable<int> CargoWeight { get; set; }
        public Nullable<int> Freight { get; set; }
        public Nullable<decimal> FreightTone { get; set; }
        public Nullable<double> FreightToneDistance { get; set; }
        public Nullable<double> TotalToneDistance { get; set; }
        public Nullable<double> TotalToneDistanceAvailable { get; set; }
        public Nullable<double> WeightLoadFactor { get; set; }
        public Nullable<double> Distance { get; set; }
        public int LegsInt { get; set; }
        public decimal FlightHourInt { get; set; }
        public int PaxChildInt { get; set; }
        public int PaxInfantInt { get; set; }
        public int PaxAdultInt { get; set; }
        public int PaxTotalInt { get; set; }
        public double PaxTotalDistRoundInt { get; set; }
        public double PaxTotalDistInt { get; set; }
        public int PaxAllInt { get; set; }
        public int TotalSeatInt { get; set; }
        public double TotalSeatDistInt { get; set; }
        public int PaxLoadInt { get; set; }
        public double TotalSeatDistRoundInt { get; set; }
        public int PaxAllWeightInt { get; set; }
        public double PaxAllWeightDistanceInt { get; set; }
        public int BaggageWeightInt { get; set; }
        public int CargoWeightInt { get; set; }
        public int FreightInt { get; set; }
        public decimal FreightToneInt { get; set; }
        public double FreightToneDistanceInt { get; set; }
        public double TotalToneDistanceInt { get; set; }
        public double TotalToneDistanceAvailableInt { get; set; }
        public double WeightLoadFactorInt { get; set; }
        public double DistanceInt { get; set; }
    }
}
