//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRegHistoryMonthly
    {
        public int Year { get; set; }
        public int Month { get; set; }
        public string YearName { get; set; }
        public string MonthName { get; set; }
        public string YearMonth { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string AircraftType { get; set; }
        public string Fleet { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string Register { get; set; }
        public Nullable<int> Legs { get; set; }
        public int Child { get; set; }
        public int Infant { get; set; }
        public int Adult { get; set; }
        public int TotalPax { get; set; }
        public int TotalPaxAll { get; set; }
        public int TotalSeat { get; set; }
        public int BlockTime { get; set; }
        public int FlightTime { get; set; }
        public Nullable<decimal> FtLeg { get; set; }
        public Nullable<decimal> BtLeg { get; set; }
    }
}
