//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightFDP
    {
        public int FDPId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public string FDPTitle { get; set; }
        public string FDPRemark { get; set; }
        public Nullable<System.DateTime> DutyStart { get; set; }
        public Nullable<System.DateTime> DutyEnd { get; set; }
        public Nullable<System.DateTime> DutyStartLocal { get; set; }
        public Nullable<System.DateTime> DutyEndLocal { get; set; }
        public Nullable<int> Sectors { get; set; }
        public string ToAirportIATA { get; set; }
        public string FromAirportIATA { get; set; }
        public Nullable<System.DateTime> DefaultReportingTime { get; set; }
        public Nullable<System.DateTime> DefaultReportingTimeLocal { get; set; }
        public Nullable<int> FDP { get; set; }
        public Nullable<int> FDPScheduled { get; set; }
        public Nullable<double> DutyScheduled { get; set; }
        public Nullable<double> Duty { get; set; }
        public Nullable<System.DateTime> RestFrom { get; set; }
        public Nullable<System.DateTime> RestFromLocal { get; set; }
        public Nullable<System.DateTime> RestUntil { get; set; }
        public Nullable<System.DateTime> RestUntilLocal { get; set; }
        public Nullable<double> MaxFDPExtended { get; set; }
        public int IsDutyOver { get; set; }
        public int ExtendedBySplitDuty { get; set; }
    }
}
