//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFLTGroup
    {
        public int Id { get; set; }
        public System.DateTime CDate { get; set; }
        public string Remark { get; set; }
        public int FirstFlightId { get; set; }
        public int LastFlightId { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> StartLocal { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<System.DateTime> EndLocal { get; set; }
        public string FirstFlightNumber { get; set; }
        public string LastFlightNumber { get; set; }
    }
}
