//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightCrewXOff
    {
        public int FDPId { get; set; }
        public int FDPItemId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int SexId { get; set; }
        public string Sex { get; set; }
        public int GroupOrder { get; set; }
        public int IsCockpit { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STDDayEnd { get; set; }
        public string FlightNumber { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public string Register { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<System.DateTime> TakeOff { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> ChocksOutLocal { get; set; }
        public Nullable<System.DateTime> ChocksInLocal { get; set; }
        public Nullable<System.DateTime> TakeOffLocal { get; set; }
        public Nullable<System.DateTime> LandingLocal { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> FlightTimeActual { get; set; }
        public Nullable<int> Fixtime { get; set; }
        public Nullable<int> SITATime { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<int> FlightStatusId { get; set; }
        public string Airline { get; set; }
        public Nullable<int> AirlineOperatorsID { get; set; }
        public string CPInstructor { get; set; }
        public string CPP1 { get; set; }
        public string CPP2 { get; set; }
        public string CPSCCM { get; set; }
        public string CPISCCM { get; set; }
        public Nullable<int> CPCrewId { get; set; }
        public Nullable<bool> SplitDuty { get; set; }
        public int NightTime { get; set; }
        public Nullable<int> DayTime { get; set; }
        public Nullable<int> NightTakeOff { get; set; }
        public Nullable<int> DayTakeOff { get; set; }
        public Nullable<int> NightLanding { get; set; }
        public Nullable<int> DayLanding { get; set; }
    }
}
