//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFormA
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public string FlightNumber { get; set; }
        public string Register { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<decimal> FlightHour { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Route { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public int PaxChild { get; set; }
        public int PaxInfant { get; set; }
        public int PaxAdult { get; set; }
        public Nullable<int> PaxTotal { get; set; }
        public Nullable<double> PaxTotalDistRound { get; set; }
        public Nullable<double> PaxTotalDist { get; set; }
        public Nullable<int> PaxAll { get; set; }
        public int TotalSeat { get; set; }
        public Nullable<double> TotalSeatDist { get; set; }
        public Nullable<int> PaxLoad { get; set; }
        public Nullable<double> TotalSeatDistRound { get; set; }
        public Nullable<int> PaxAllWeight { get; set; }
        public Nullable<double> PaxAllWeightDistance { get; set; }
        public string DayName { get; set; }
        public string YearName { get; set; }
        public Nullable<int> Year { get; set; }
        public string MonthName { get; set; }
        public Nullable<int> Month { get; set; }
        public string YearMonthName { get; set; }
        public string PDate { get; set; }
        public string PYearName { get; set; }
        public Nullable<int> PYear { get; set; }
        public string PMonthName { get; set; }
        public Nullable<int> PMonth { get; set; }
        public string PDayName { get; set; }
        public string PYearMonthName { get; set; }
        public Nullable<int> Quarter { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public Nullable<int> Freight { get; set; }
        public Nullable<decimal> FreightTone { get; set; }
        public Nullable<double> FreightToneDistance { get; set; }
        public Nullable<double> Mail { get; set; }
        public Nullable<double> TotalToneDistance { get; set; }
        public Nullable<double> TotalToneDistanceAvailable { get; set; }
        public Nullable<double> WeightLoadFactor { get; set; }
        public Nullable<double> Distance { get; set; }
        public int IsDom { get; set; }
        public Nullable<int> FlightMinutes { get; set; }
    }
}
