//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDutyFDPDetail
    {
        public System.DateTime CDate { get; set; }
        public Nullable<int> CDay { get; set; }
        public Nullable<System.DateTime> DatePart { get; set; }
        public int FDPId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> DutyStart { get; set; }
        public Nullable<System.DateTime> DutyEnd { get; set; }
        public Nullable<System.DateTime> DutyStartLocal { get; set; }
        public Nullable<System.DateTime> DutyEndLocal { get; set; }
        public Nullable<int> DateStartYear { get; set; }
        public Nullable<int> DateStartMonth { get; set; }
        public Nullable<int> DateStartDay { get; set; }
        public Nullable<int> DateEndDay { get; set; }
        public Nullable<int> DateEndMonth { get; set; }
        public string FDPTitle { get; set; }
        public string FDPRemark { get; set; }
        public string DutyTypeTitle { get; set; }
        public int DutyType { get; set; }
        public string JobGroup { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroupCode { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> DurationLocal { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> MaleFemaleError { get; set; }
        public Nullable<int> MatchingListErrors { get; set; }
    }
}
