//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewImportPlan
    {
        public System.DateTime Date { get; set; }
        public string Base { get; set; }
        public int BaseId { get; set; }
        public string Type { get; set; }
        public string Reg { get; set; }
        public int RegId { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> AircraftTypeId { get; set; }
        public string No { get; set; }
        public string From { get; set; }
        public int FromId { get; set; }
        public string To { get; set; }
        public int ToId { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public string Duration { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<System.DateTime> STDUtc { get; set; }
        public Nullable<System.DateTime> STAUtc { get; set; }
        public string Line { get; set; }
        public int LineId { get; set; }
        public Nullable<int> RouteId { get; set; }
    }
}
