//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightCrewArchive
    {
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public int IsCockpit { get; set; }
        public int SexId { get; set; }
        public string Sex { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string Position { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string FlightNo { get; set; }
        public int Id { get; set; }
        public int GroupOrder { get; set; }
        public string Code { get; set; }
    }
}
