//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRosterReport
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateLocal { get; set; }
        public string FltNo { get; set; }
        public string Route { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public string Register { get; set; }
        public string AircraftType { get; set; }
        public string IP { get; set; }
        public string OBS { get; set; }
        public string P1 { get; set; }
        public string P2 { get; set; }
        public string SAFETY { get; set; }
        public string SCCM { get; set; }
        public string CCM1 { get; set; }
        public string CCM2 { get; set; }
        public string CCM3 { get; set; }
    }
}
