//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewBoardSummary
    {
        public System.DateTime Date { get; set; }
        public Nullable<int> TotalFlight { get; set; }
        public Nullable<int> Departed { get; set; }
        public Nullable<int> Arrived { get; set; }
        public Nullable<int> Diverted { get; set; }
        public Nullable<int> Canceled { get; set; }
        public int BlockTime { get; set; }
        public int FlightTimeActual { get; set; }
        public int FlightTime { get; set; }
        public int FixTime { get; set; }
        public int SITATime { get; set; }
        public int Delay { get; set; }
        public int Pax { get; set; }
        public int PaxAdult { get; set; }
        public int PaxChild { get; set; }
        public int PaxInfant { get; set; }
        public decimal PaxLoad { get; set; }
        public int TotalSeat { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public int BaggageCount { get; set; }
        public int CargoCount { get; set; }
        public long CargoCost { get; set; }
        public int FreeAWBCount { get; set; }
        public int FreeAWBWeight { get; set; }
        public int NoShowCount { get; set; }
        public int NoShowPieces { get; set; }
        public int NoGoCount { get; set; }
        public int NoGoPieces { get; set; }
        public int DSBreakfast { get; set; }
        public int DSWarmFood { get; set; }
        public int DSColdFood { get; set; }
        public int DSRefreshment { get; set; }
        public decimal FuelActual { get; set; }
        public decimal FuelUplift { get; set; }
        public int YClass { get; set; }
        public int CClass { get; set; }
        public int PaxAdult50 { get; set; }
        public int PaxChild50 { get; set; }
        public int PaxInfant50 { get; set; }
        public int PaxAdult100 { get; set; }
        public int PaxChild100 { get; set; }
        public int PaxInfant100 { get; set; }
        public int PaxVIP { get; set; }
        public int PaxCIP { get; set; }
        public int PaxHUM { get; set; }
        public int PaxUM { get; set; }
        public int PaxAVI { get; set; }
        public int PaxWCHR { get; set; }
        public int PaxSTRC { get; set; }
        public int FreeAWBPieces { get; set; }
        public int CargoPieces { get; set; }
        public int PaxPIRLost { get; set; }
        public int PaxPIRDamage { get; set; }
        public int PaxPIRFound { get; set; }
        public int CargoPIRLost { get; set; }
        public int CargoPIRDamage { get; set; }
        public int CargoPIRFound { get; set; }
        public int LimitTag { get; set; }
        public int RushTag { get; set; }
    }
}
