//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCertification
    {
        public int Id { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string TypeTitle { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateIssue { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<System.DateTime> DateIRValid { get; set; }
        public Nullable<int> AcTypeId { get; set; }
        public string AcType { get; set; }
        public string Rating { get; set; }
        public Nullable<int> Class { get; set; }
        public string Limitation { get; set; }
        public string EmployedBy { get; set; }
        public Nullable<int> EmployedById { get; set; }
        public string Occupation { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> PersonId { get; set; }
        public bool AirPocket { get; set; }
        public string Title { get; set; }
        public string No { get; set; }
        public Nullable<int> Remain { get; set; }
        public int Expiring { get; set; }
    }
}
