//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCrewFlight
    {
        public int FDPId { get; set; }
        public Nullable<int> Id { get; set; }
        public int DutyType { get; set; }
        public string DutyTypeTitle { get; set; }
        public int FDPItemId { get; set; }
        public Nullable<int> CrewId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string Position { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int SexId { get; set; }
        public string Sex { get; set; }
        public int GroupOrder { get; set; }
        public int IsCockpit { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<System.DateTime> STDDayLocal { get; set; }
        public Nullable<System.DateTime> STADayLocal { get; set; }
        public string FlightNumber { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public string Register { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<System.DateTime> BlockOff { get; set; }
        public Nullable<System.DateTime> BlockOn { get; set; }
        public Nullable<System.DateTime> TakeOff { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> BlockOffLocal { get; set; }
        public Nullable<System.DateTime> BlockOnLocal { get; set; }
        public Nullable<System.DateTime> TakeOffLocal { get; set; }
        public Nullable<System.DateTime> LandingLocal { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> ScheduledFlightTime { get; set; }
        public Nullable<int> FPFlightTime { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public Nullable<int> Freight { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<int> FlightStatusId { get; set; }
        public string Airline { get; set; }
        public Nullable<int> AirlineOperatorsID { get; set; }
        public Nullable<int> CPCrewId { get; set; }
        public string CPInstructor { get; set; }
        public string CPP1 { get; set; }
        public string CPP2 { get; set; }
        public string CPSCCM { get; set; }
        public string CPISCCM { get; set; }
        public Nullable<bool> SplitDuty { get; set; }
        public int NightTime { get; set; }
        public Nullable<int> DayTime { get; set; }
        public Nullable<int> DelayBlockOff { get; set; }
        public Nullable<int> NightTakeOff { get; set; }
        public Nullable<int> DayTakeOff { get; set; }
        public Nullable<int> NightLanding { get; set; }
        public Nullable<int> DayLanding { get; set; }
        public Nullable<int> JLUserId { get; set; }
        public Nullable<int> JLApproverId { get; set; }
        public Nullable<System.DateTime> JLDate { get; set; }
        public Nullable<System.DateTime> JLDateApproved { get; set; }
        public string JLNo { get; set; }
        public string JLUser { get; set; }
        public string JLApprover { get; set; }
        public int IsJL { get; set; }
        public int IsJLApproved { get; set; }
        public Nullable<int> FuelUnitID { get; set; }
        public Nullable<decimal> FuelRemaining { get; set; }
        public Nullable<decimal> FuelUplift { get; set; }
        public Nullable<decimal> FuelUsed { get; set; }
        public Nullable<decimal> FuelTotal { get; set; }
        public Nullable<int> PaxAdult { get; set; }
        public Nullable<int> PaxChild { get; set; }
        public Nullable<int> PaxInfant { get; set; }
        public Nullable<int> PaxTotal { get; set; }
        public Nullable<int> PaxRevenued { get; set; }
        public string SerialNo { get; set; }
        public string LTR { get; set; }
        public Nullable<decimal> RVSM_GND_CPT { get; set; }
        public Nullable<decimal> RVSM_GND_STBY { get; set; }
        public Nullable<decimal> RVSM_GND_FO { get; set; }
        public Nullable<decimal> RVSM_FLT_CPT { get; set; }
        public Nullable<decimal> RVSM_FLT_STBY { get; set; }
        public Nullable<decimal> RVSM_FLT_FO { get; set; }
        public Nullable<decimal> CARGO { get; set; }
        public Nullable<decimal> FuelDensity { get; set; }
        public string CommanderNote { get; set; }
        public Nullable<bool> AttASR { get; set; }
        public Nullable<bool> AttVoyageReport { get; set; }
        public Nullable<bool> AttRepositioning1 { get; set; }
        public Nullable<bool> AttRepositioning2 { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<bool> IsSynced { get; set; }
        public string PF { get; set; }
        public string IPName { get; set; }
        public Nullable<int> IPId { get; set; }
        public string IPScheduleName { get; set; }
        public string P1Name { get; set; }
        public Nullable<int> P1Id { get; set; }
        public string P1ScheduleName { get; set; }
        public string P2Name { get; set; }
        public Nullable<int> P2Id { get; set; }
        public string P2ScheduleName { get; set; }
        public string PIC { get; set; }
        public Nullable<int> PICId { get; set; }
        public string SIC { get; set; }
        public Nullable<int> SICId { get; set; }
        public Nullable<System.DateTime> JLDatePICApproved { get; set; }
        public Nullable<System.DateTime> IStart { get; set; }
        public string JLSignedBy { get; set; }
        public string ALT1 { get; set; }
        public string ALT2 { get; set; }
        public string ALT3 { get; set; }
        public string ALT4 { get; set; }
        public string ALT5 { get; set; }
        public string ATCPlan { get; set; }
        public string ATL { get; set; }
    }
}
