//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppCertificate
    {
        public int CrewId { get; set; }
        public int PersonId { get; set; }
        public int TypeId { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<int> EXPDay { get; set; }
        public Nullable<int> EXPMonth { get; set; }
        public Nullable<int> EXPYear { get; set; }
        public Nullable<int> Remain { get; set; }
        public string Title { get; set; }
        public string Remark { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public int IsCockpit { get; set; }
        public int IsCabin { get; set; }
        public string Status { get; set; }
        public int StatusId { get; set; }
    }
}
