//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookFile
    {
        public int Id { get; set; }
        public int BookId { get; set; }
        public int DocumentId { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ChapterId { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
