//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayGP
    {
        public System.DateTime GDate { get; set; }
        public string PDate { get; set; }
        public string PYearName { get; set; }
        public Nullable<int> PYear { get; set; }
        public string PMonthName { get; set; }
        public Nullable<int> PMonth { get; set; }
        public string PDayName { get; set; }
        public Nullable<int> UtcDiff { get; set; }
        public Nullable<System.DateTime> LocalDate { get; set; }
        public string PeriodFixTime { get; set; }
        public Nullable<int> PDate2 { get; set; }
    }
}
