//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelayXMLItem
    {
        public int Id { get; set; }
        public string XmlId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> HH { get; set; }
        public Nullable<int> MM { get; set; }
        public string Code { get; set; }
        public Nullable<int> CodeId { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
    }
}
