//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpFlight
    {
        public string PersianDate { get; set; }
        public Nullable<int> PersianYear { get; set; }
        public string PersianMonthName { get; set; }
        public Nullable<int> PersianMonth { get; set; }
        public string PersianDayName { get; set; }
        public Nullable<int> PersianDay { get; set; }
        public int Id { get; set; }
        public Nullable<int> RegisterId { get; set; }
        public Nullable<int> FlightStatusId { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> AircraftTypeId { get; set; }
        public string FlightNo { get; set; }
        public Nullable<int> OriginId { get; set; }
        public Nullable<int> DestinationId { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public string OriginICAO { get; set; }
        public string DestinationICAO { get; set; }
        public string Register { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<System.DateTime> DepartureDay { get; set; }
        public Nullable<System.DateTime> ArrivalDay { get; set; }
        public Nullable<System.DateTime> DepartureDayLocal { get; set; }
        public Nullable<System.DateTime> ArrivalDayLocal { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
    }
}
