//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDPItem
    {
        public int Id { get; set; }
        public int FDPId { get; set; }
        public Nullable<int> FlightId { get; set; }
        public bool IsSector { get; set; }
        public Nullable<int> SplitDutyPairId { get; set; }
        public Nullable<bool> SplitDuty { get; set; }
        public Nullable<bool> IsPositioning { get; set; }
        public Nullable<bool> IsOff { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> RosterPositionId { get; set; }
        public Nullable<System.DateTime> Pickup { get; set; }
    
        public virtual FDP FDP { get; set; }
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
