//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightCharterer
    {
        public int Id { get; set; }
        public int FlightId { get; set; }
        public int ChartererId { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> Infanct { get; set; }
    
        public virtual Charterer Charterer { get; set; }
        public virtual FlightInformation FlightInformation { get; set; }
    }
}
