//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormVacation
    {
        public int Id { get; set; }
        public int Reason { get; set; }
        public string ReasonStr { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string OperationRemak { get; set; }
        public string SchedulingRemark { get; set; }
        public Nullable<System.DateTime> DateStatus { get; set; }
        public string Status { get; set; }
        public Nullable<int> OperatorId { get; set; }
    }
}
