//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTLFlightTimeRatioMonthly
    {
        public int CrewId { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public Nullable<int> ScheduledFlightTime { get; set; }
        public Nullable<int> CNT { get; set; }
        public Nullable<decimal> Ratio { get; set; }
    }
}
