//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTLSummary
    {
        public System.DateTime CDate { get; set; }
        public int CrewId { get; set; }
        public Nullable<double> Duty7 { get; set; }
        public Nullable<double> Duty14 { get; set; }
        public Nullable<double> Duty28 { get; set; }
        public Nullable<double> Flight28 { get; set; }
        public Nullable<double> FlightYear { get; set; }
        public Nullable<double> FlightCYear { get; set; }
    }
}
