//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaSessionItemTemp
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<System.DateTime> DateFromUtc { get; set; }
        public Nullable<System.DateTime> DateToUtc { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FDPId { get; set; }
    
        public virtual IdeaSessionTemp IdeaSessionTemp { get; set; }
    }
}
