//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IdeaSessionUpdateError
    {
        public int Id { get; set; }
        public Nullable<int> SessionItemId { get; set; }
        public Nullable<int> FDPId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string Name { get; set; }
        public string Route { get; set; }
        public string Flights { get; set; }
        public Nullable<System.DateTime> DutyStart { get; set; }
        public Nullable<System.DateTime> DutyEnd { get; set; }
        public Nullable<System.DateTime> RestUntil { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public Nullable<System.DateTime> SessionDateFrom { get; set; }
        public Nullable<System.DateTime> SessionDateTo { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
    }
}
