//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginInfo
    {
        public int Id { get; set; }
        public string User { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public string Info { get; set; }
        public string IP { get; set; }
        public string LocationCity { get; set; }
    }
}
