//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FLYEntities : DbContext
    {
        public FLYEntities()
            : base("name=FLYEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RptFlight> RptFlights { get; set; }
        public virtual DbSet<DlyGrpFlight> DlyGrpFlights { get; set; }
        public virtual DbSet<ViewLegTime> ViewLegTimes { get; set; }
        public virtual DbSet<ExpFlight> ExpFlights { get; set; }
        public virtual DbSet<IdeaSession> IdeaSessions { get; set; }
        public virtual DbSet<IdeaAll> IdeaAlls { get; set; }
        public virtual DbSet<IdeaUnique> IdeaUniques { get; set; }
        public virtual DbSet<ViewIdeaUniqueLast> ViewIdeaUniqueLasts { get; set; }
        public virtual DbSet<ThirdPartySyncHistory> ThirdPartySyncHistories { get; set; }
        public virtual DbSet<MVT> MVTs { get; set; }
        public virtual DbSet<ViewDelayCode> ViewDelayCodes { get; set; }
        public virtual DbSet<ViewFlightDelayCode> ViewFlightDelayCodes { get; set; }
        public virtual DbSet<MVTAPI> MVTAPIs { get; set; }
        public virtual DbSet<FDP> FDPs { get; set; }
        public virtual DbSet<FDPItem> FDPItems { get; set; }
        public virtual DbSet<IdeaSessionItem> IdeaSessionItems { get; set; }
        public virtual DbSet<ViewEmployeeLight> ViewEmployeeLights { get; set; }
        public virtual DbSet<ViewFDPRest> ViewFDPRests { get; set; }
        public virtual DbSet<IdeaSessionUpdateError> IdeaSessionUpdateErrors { get; set; }
        public virtual DbSet<ViewIdeaSessionUpdateError> ViewIdeaSessionUpdateErrors { get; set; }
        public virtual DbSet<ViewTrainingDuty> ViewTrainingDuties { get; set; }
        public virtual DbSet<IdeaSessionItemTemp> IdeaSessionItemTemps { get; set; }
        public virtual DbSet<IdeaSessionTemp> IdeaSessionTemps { get; set; }
        public virtual DbSet<ViewFDPIdea> ViewFDPIdeas { get; set; }
        public virtual DbSet<ViewIdeaSessionItemX> ViewIdeaSessionItemXes { get; set; }
        public virtual DbSet<BookFile> BookFiles { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<ViewBookFile> ViewBookFiles { get; set; }
        public virtual DbSet<EFBDSPRelease> EFBDSPReleases { get; set; }
        public virtual DbSet<OFPImportItem> OFPImportItems { get; set; }
        public virtual DbSet<OFPImportProp> OFPImportProps { get; set; }
        public virtual DbSet<LoginInfo> LoginInfoes { get; set; }
        public virtual DbSet<EFBFlightIrregularity> EFBFlightIrregularities { get; set; }
        public virtual DbSet<EFBReason> EFBReasons { get; set; }
        public virtual DbSet<AppLeg> AppLegs { get; set; }
        public virtual DbSet<ViewFlightCrewNewX> ViewFlightCrewNewXes { get; set; }
        public virtual DbSet<PersonHistory> PersonHistories { get; set; }
        public virtual DbSet<ViewTrainingSMSHistory> ViewTrainingSMSHistories { get; set; }
        public virtual DbSet<AppCrewFlight> AppCrewFlights { get; set; }
        public virtual DbSet<Ac_MSN> Ac_MSN { get; set; }
        public virtual DbSet<ViewFlightCrewNew> ViewFlightCrewNews { get; set; }
        public virtual DbSet<RosterDailyReport> RosterDailyReports { get; set; }
        public virtual DbSet<FTLSummary> FTLSummaries { get; set; }
        public virtual DbSet<AppFTL> AppFTLs { get; set; }
        public virtual DbSet<AppCrewTime> AppCrewTimes { get; set; }
        public virtual DbSet<EFBASR> EFBASRs { get; set; }
        public virtual DbSet<EFBVoyageReport> EFBVoyageReports { get; set; }
        public virtual DbSet<AppLegOP> AppLegOPS { get; set; }
        public virtual DbSet<ViewRosterCrewCount> ViewRosterCrewCounts { get; set; }
        public virtual DbSet<OFPImport> OFPImports { get; set; }
        public virtual DbSet<ViewFDRReport> ViewFDRReports { get; set; }
        public virtual DbSet<FTLFlightTime> FTLFlightTimes { get; set; }
        public virtual DbSet<AppFTLAb> AppFTLAbs { get; set; }
        public virtual DbSet<FTLFlightTimeRatioMonthly> FTLFlightTimeRatioMonthlies { get; set; }
        public virtual DbSet<ViewCrewTimeDetail> ViewCrewTimeDetails { get; set; }
        public virtual DbSet<ViewCrewValidFTL> ViewCrewValidFTLs { get; set; }
        public virtual DbSet<ViewCrewDutyTimeLine> ViewCrewDutyTimeLines { get; set; }
        public virtual DbSet<DayGP> DayGPs { get; set; }
        public virtual DbSet<ViewEFBASR> ViewEFBASRs { get; set; }
        public virtual DbSet<AppCertificate> AppCertificates { get; set; }
        public virtual DbSet<ViewFlightCockpit> ViewFlightCockpits { get; set; }
        public virtual DbSet<RptAirportDaily> RptAirportDailies { get; set; }
        public virtual DbSet<FlightCharterer> FlightCharterers { get; set; }
        public virtual DbSet<Charterer> Charterers { get; set; }
        public virtual DbSet<ViewFlightCharterer> ViewFlightCharterers { get; set; }
        public virtual DbSet<ViewTimeTable> ViewTimeTables { get; set; }
        public virtual DbSet<ViewFlightInformation> ViewFlightInformations { get; set; }
        public virtual DbSet<ViewCrewList> ViewCrewLists { get; set; }
        public virtual DbSet<ReportRoster> ReportRosters { get; set; }
        public virtual DbSet<ViewCrewDuty> ViewCrewDuties { get; set; }
        public virtual DbSet<NiraHistory> NiraHistories { get; set; }
        public virtual DbSet<ViewFlightDelay> ViewFlightDelays { get; set; }
        public virtual DbSet<ViewFlightDaily> ViewFlightDailies { get; set; }
        public virtual DbSet<FltFMI> FltFMIS { get; set; }
        public virtual DbSet<Airport> Airports { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<FlightInformation> FlightInformations { get; set; }
        public virtual DbSet<ViewJobGroup> ViewJobGroups { get; set; }
        public virtual DbSet<DelayCode> DelayCodes { get; set; }
        public virtual DbSet<FlightDelay> FlightDelays { get; set; }
        public virtual DbSet<DelayXML> DelayXMLs { get; set; }
        public virtual DbSet<DelayXMLItem> DelayXMLItems { get; set; }
        public virtual DbSet<FormVacation> FormVacations { get; set; }
        public virtual DbSet<ViewFormVacation> ViewFormVacations { get; set; }
    }
}
