//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NiraHistory
    {
        public int Id { get; set; }
        public string FLIGHT { get; set; }
        public string CHTIME { get; set; }
        public string NEWAIRCRAFT { get; set; }
        public string NEWSTATUS { get; set; }
        public Nullable<System.DateTime> DateSend { get; set; }
        public Nullable<System.DateTime> DateReplied { get; set; }
        public string Remark { get; set; }
        public Nullable<int> FlightId { get; set; }
        public Nullable<int> FlightStatusId { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public string Register { get; set; }
    }
}
