//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OFPImportItem
    {
        public int Id { get; set; }
        public int OFPId { get; set; }
        public string Line { get; set; }
    
        public virtual OFPImport OFPImport { get; set; }
    }
}
