//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewTimeTable
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string FlightType { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Customer { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Register { get; set; }
        public string AircraftType { get; set; }
        public int PaxAdult { get; set; }
        public int PaxChild { get; set; }
        public int PaxInfant { get; set; }
        public Nullable<int> TotalPax { get; set; }
        public Nullable<decimal> FuelDeparture { get; set; }
        public Nullable<int> CargoCount { get; set; }
        public int CargoWeight { get; set; }
        public int BaggageWeight { get; set; }
        public Nullable<int> BaggageCount { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STDDayLocal { get; set; }
        public string PDate { get; set; }
        public string PDateLocal { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> FlightTimeActual { get; set; }
        public Nullable<int> SITATime { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<double> ActualFlightTimeToSITA { get; set; }
        public string IP { get; set; }
        public string Captain { get; set; }
        public string IPName { get; set; }
        public string CaptainName { get; set; }
        public int IPId { get; set; }
        public int CaptainId { get; set; }
        public int FlightStatusID { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<System.DateTime> JLOffBlock { get; set; }
        public Nullable<System.DateTime> JLOnBlock { get; set; }
        public Nullable<System.DateTime> JLTakeOff { get; set; }
        public Nullable<System.DateTime> JLLanding { get; set; }
        public Nullable<int> PFLR { get; set; }
        public Nullable<int> JLBlockTime { get; set; }
        public Nullable<int> JLFlightTime { get; set; }
        public string Cockpit { get; set; }
        public string Cabin { get; set; }
        public string ChrCode { get; set; }
        public string ChrTitle { get; set; }
        public Nullable<int> ChrCapacity { get; set; }
        public Nullable<int> ChrAdult { get; set; }
        public Nullable<int> ChrChild { get; set; }
        public Nullable<int> ChrInfant { get; set; }
    }
}
