//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewIdeaUniqueLast
    {
        public int Id { get; set; }
        public string IdeaId { get; set; }
        public Nullable<long> Rank { get; set; }
        public string NID { get; set; }
        public string PID { get; set; }
        public string CourseCode { get; set; }
        public string CourseTitle { get; set; }
        public string CourseType { get; set; }
        public string ClassID { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> DateCreate { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string CrewPID { get; set; }
        public Nullable<int> GroupId { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public string CrewNID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Name { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<int> IsCockpit { get; set; }
        public Nullable<int> IsCabin { get; set; }
    }
}
