//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFlightCharterer
    {
        public Nullable<System.DateTime> ChocksIn { get; set; }
        public Nullable<System.DateTime> Landing { get; set; }
        public Nullable<System.DateTime> Takeoff { get; set; }
        public Nullable<System.DateTime> ChocksOut { get; set; }
        public Nullable<System.DateTime> STD { get; set; }
        public Nullable<System.DateTime> STA { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> RegisterID { get; set; }
        public Nullable<int> FlightStatusID { get; set; }
        public Nullable<int> FlightTypeID { get; set; }
        public string AircraftType { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string FlightNumber { get; set; }
        public Nullable<int> FromAirport { get; set; }
        public string FromAirportICAO { get; set; }
        public Nullable<int> ToAirport { get; set; }
        public string ToAirportICAO { get; set; }
        public string FromAirportIATA { get; set; }
        public string ToAirportIATA { get; set; }
        public string Register { get; set; }
        public string FlightStatus { get; set; }
        public Nullable<System.DateTime> STDDay { get; set; }
        public Nullable<System.DateTime> STADay { get; set; }
        public Nullable<System.DateTime> DepartureLocal { get; set; }
        public Nullable<System.DateTime> ArrivalLocal { get; set; }
        public Nullable<int> BlockTime { get; set; }
        public Nullable<int> FlightTime { get; set; }
        public Nullable<int> PaxChild { get; set; }
        public Nullable<int> PaxInfant { get; set; }
        public Nullable<int> PaxAdult { get; set; }
        public Nullable<int> TotalSeat { get; set; }
        public Nullable<System.DateTime> FlightDate { get; set; }
        public Nullable<int> Freight { get; set; }
        public int BaggageWeight { get; set; }
        public int CargoWeight { get; set; }
        public Nullable<int> CargoCount { get; set; }
        public Nullable<int> BaggageCount { get; set; }
        public Nullable<int> TotalPaxRev { get; set; }
        public Nullable<int> TotalPax { get; set; }
        public string Code { get; set; }
        public string Title1 { get; set; }
        public string NiraCode { get; set; }
        public string Title2 { get; set; }
        public Nullable<int> Book { get; set; }
        public Nullable<int> Capacity { get; set; }
        public Nullable<int> Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> Infant { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> TotalRev { get; set; }
        public Nullable<decimal> RevPercent { get; set; }
        public string Remark { get; set; }
        public int FlightId { get; set; }
        public int ChartererId { get; set; }
        public int Id { get; set; }
        public string PDate { get; set; }
    }
}
