//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewRosterCrewCount
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateLocal { get; set; }
        public string FltNo { get; set; }
        public string Route { get; set; }
        public Nullable<System.DateTime> STDLocal { get; set; }
        public Nullable<System.DateTime> STALocal { get; set; }
        public string Register { get; set; }
        public Nullable<int> CockpitCount { get; set; }
        public Nullable<int> CabinCount { get; set; }
    }
}
