//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirpocketAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCrewDutyTimeLine
    {
        public int Id { get; set; }
        public int DutyType { get; set; }
        public string DutyTypeTitle { get; set; }
        public Nullable<int> CrewId { get; set; }
        public string ScheduleName { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string JobGroup { get; set; }
        public string JobGroupCode { get; set; }
        public Nullable<int> JobGroupId { get; set; }
        public int IsCockpit { get; set; }
        public string JobGroup2 { get; set; }
        public int GroupOrder { get; set; }
        public string ValidTypes { get; set; }
        public Nullable<int> BaseAirportId { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> RankId { get; set; }
        public string Rank { get; set; }
        public Nullable<System.DateTime> DateStart { get; set; }
        public Nullable<System.DateTime> DateEnd { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<System.DateTime> Start { get; set; }
        public Nullable<System.DateTime> End { get; set; }
        public Nullable<System.DateTime> StartLocal { get; set; }
        public Nullable<System.DateTime> EndLocal { get; set; }
        public Nullable<int> YearLocal { get; set; }
        public Nullable<int> MonthLocal { get; set; }
        public Nullable<System.DateTime> RestTo { get; set; }
        public Nullable<System.DateTime> RestToLocal { get; set; }
        public Nullable<int> TemplateId { get; set; }
        public string Key { get; set; }
        public Nullable<System.DateTime> InitStart { get; set; }
        public Nullable<System.DateTime> InitEnd { get; set; }
        public string InitFlts { get; set; }
        public string InitRoute { get; set; }
        public string InitFromIATA { get; set; }
        public string InitNo { get; set; }
        public string InitKey { get; set; }
        public Nullable<int> InitHomeBase { get; set; }
        public string InitRank { get; set; }
        public Nullable<int> InitIndex { get; set; }
        public string InitGroup { get; set; }
        public string InitFlights { get; set; }
        public Nullable<int> Extension { get; set; }
        public Nullable<double> Split { get; set; }
        public string Remark { get; set; }
        public string Remark2 { get; set; }
        public Nullable<decimal> MaxFDP { get; set; }
        public Nullable<int> DurationDuty { get; set; }
        public Nullable<int> DurationFDP { get; set; }
        public int IsFDPOver { get; set; }
        public Nullable<int> InteruptedId { get; set; }
    }
}
