//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPAGriffinAPI.IdeaServiceRef {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IdeaServiceRef.TrainingWSSoap")]
    public interface TrainingWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonnelData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPersonnelData(string title, string personnelCode, string ideaAuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonnelData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPersonnelDataAsync(string title, string personnelCode, string ideaAuthToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrainingDurationSum", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetTrainingDurationSum(string type, string personnelCode, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTrainingDurationSum", ReplyAction="*")]
        System.Threading.Tasks.Task<string> GetTrainingDurationSumAsync(string type, string personnelCode, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetData(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetData", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonnelDataByDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPersonnelDataByDate(string Title, string FromDate, string ToDate, string PersonnelCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPersonnelDataByDate", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetPersonnelDataByDateAsync(string Title, string FromDate, string ToDate, string PersonnelCode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TrainingWSSoapChannel : EPAGriffinAPI.IdeaServiceRef.TrainingWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TrainingWSSoapClient : System.ServiceModel.ClientBase<EPAGriffinAPI.IdeaServiceRef.TrainingWSSoap>, EPAGriffinAPI.IdeaServiceRef.TrainingWSSoap {
        
        public TrainingWSSoapClient() {
        }
        
        public TrainingWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TrainingWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TrainingWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPersonnelData(string title, string personnelCode, string ideaAuthToken) {
            return base.Channel.GetPersonnelData(title, personnelCode, ideaAuthToken);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPersonnelDataAsync(string title, string personnelCode, string ideaAuthToken) {
            return base.Channel.GetPersonnelDataAsync(title, personnelCode, ideaAuthToken);
        }
        
        public string GetTrainingDurationSum(string type, string personnelCode, string year) {
            return base.Channel.GetTrainingDurationSum(type, personnelCode, year);
        }
        
        public System.Threading.Tasks.Task<string> GetTrainingDurationSumAsync(string type, string personnelCode, string year) {
            return base.Channel.GetTrainingDurationSumAsync(type, personnelCode, year);
        }
        
        public System.Data.DataSet GetData(string title) {
            return base.Channel.GetData(title);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetDataAsync(string title) {
            return base.Channel.GetDataAsync(title);
        }
        
        public System.Data.DataSet GetPersonnelDataByDate(string Title, string FromDate, string ToDate, string PersonnelCode) {
            return base.Channel.GetPersonnelDataByDate(Title, FromDate, ToDate, PersonnelCode);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetPersonnelDataByDateAsync(string Title, string FromDate, string ToDate, string PersonnelCode) {
            return base.Channel.GetPersonnelDataByDateAsync(Title, FromDate, ToDate, PersonnelCode);
        }
    }
}
